package com.sudhanshu.profileservice.dto;

public enum EventType {

	VIEW_START,
	GOAL_SCORED,
	AD_IMPRESSION,
	VIDEO_WATCH,
	VIDEO_PAUSE,
	VIDEO_RESUME,
	VIDEO_COMPLETE,
	USER_LOGIN,
	USER_LOGOUT,
	SUBSCRIPTION_CREATED,
	SUBSCRIPTION_CANCELLED,
	SUBSCRIPTION_RENEWED,
	CONTENT_RATED,
	CONTENT_LIKED,
	SEARCH_PERFORMED,
	PLAYLIST_CREATED,
	WATCHLIST_ADDED
}
