spring:
  application:
    name: report-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/reports_db?useSSl=false&allowPublicKeyRetrieval=true&serverTimeZone=IST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: report_user
    password: report_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:0}

eureka:
  client:
    ServiceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appName: report-service
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: ${server.port}
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,routes
      base-path: /actuator  # Default
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
info:
  env:
    enabled: true
  git:
    mode: simple

resilience4j:
  circuitbreaker:
    instances:
      event-stats-cb:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED