server:
  port: 8065
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: EVENT-SERVICE
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=0
        - id: PROFILE-SERVICE
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/user-profiles/**
        - id: REPORT-SERVICE
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/reports/**
        - id: maintenance-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/**
            - After=2026-01-01T20:30:00+05:30[Asia/Kolkata]
            - Before=2026-01-01T21:00:00+05:30[Asia/Kolkata]
          filters:
            - SetStatus=503
            - AddResponseHeader=X-Message, On Maintenance
  security:
    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: auth-server
#            client-id: gateway-client
#            client-secret: gateway-secret
#            authorization-grant-type: client_credentials
       resourceserver:
          jwt:
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            issuer-uri: http://localhost:9000
#        provider:
#          auth-server:
#            token-uri: http://localhost:9000/oauth2/token
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      appName: gateway-service
      preferIpAddress: true
      instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,gateway,routes,mappings,loggers
  endpoint:
    health:
      show-details: always
      enabled: true
    gateway:
      enabled: true  # Gateway Actuator ONLY
    shutdown:
      enabled: false
  info:
    git:
      mode: simple
    env:
      enabled: true

