management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,routes
      base-path: /actuator  # Default
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false